# Generated by Django 3.2.9 on 2022-05-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musics',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
