# Generated by Django 3.2.9 on 2022-05-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_musics_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='musics',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
